services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comparacion-productos-api
    env_file:
      - ./environments/.env.local
    environment:
      DB_MS_HOST: db
      DB_MS_PORT: 5432
      DB_MS_DB: productos
      DB_MS_USER: postgres
      DB_MS_PASS: 123456
    command: ["node", "dist/server.js", "--local"]
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: postgres_productos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: productos
    ports:
      - "5432:5432"
    volumes:
      - ./query.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d productos"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
